### ISSUE TITLE
Google Grid Gallery Jumpy on iPhones

### ISSUE THREAD

**Issue by vagu71** [BoldGrid/vacation#3]
The gallery appears to be real jumpy when played with on Chrome and Safari on iPhones. Is there a known fix for this issue?

**Comment by bwmarkle** [comment]
Hi @vagu71, I'm not too familiar with Google Grid Gallery... Can you share the URL to the page that's having the issue? We can take a look and try to get a better idea of what's happening.

**Comment by vagu71** [comment]
Hi @bwmarkle, have a look at this link https://www.boldgrid.com/creating-image-galleries-with-boldgrids-image-gallery-plugin/. When you create a page with a masonry gallery, the code uses the google grid gallery. Which is jumpy on iphone browsers. I ended us using a different pure css masonry using the same custom field gallery data. Looks good now.
